name: Read Hello File

on:
    push:
        branches:
            - main

jobs:
    read-file:
        runs-on: ubuntu-latest
        
        steps:

            - name: Checkout code
              uses: actions/checkout@v4

            - name: Display hello.txt content
              run: |
                echo "Reading hello.txt content..."
                cat hello.txt




